# image will be published to ghcr.io/<user>/<name>
name: cosmicplasmic
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://raw.githubusercontent.com/arashsm79/vscodium-rpm-repo/main/vscodium.repo
      
    install:
      - tuned
      - gnome-keyring
      - adobe-source-code-pro-fonts
      - alacritty
      - android-tools
      - autossh
      - bash-color-prompt
      - bat
      - bcache-tools
      - btrfs-progs
      - cascadia-code-fonts
      - cifs-utils
      - cmatrix
      - codium
      - containerd.io
      - cryptsetup
      - dbus-x11
      - desktop-file-utils
      - dmidecode
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - dua-cli
      - edk2-ovmf
      - evtest
      - evtest
      - eza
      - fastfetch
      - fd-find
      - firewall-config
      - fish
      - fish
      - flatpak
      - fuse-sshfs
      - gcc
      - genisoimage
      - git
      - glx-utils
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - gwe
      - hplip
      - ibm-plex-mono-fonts
      - ifuse
      - input-remapper
      - iotop
      - jetbrains-mono-fonts-all
      - libappindicator
      - libimobiledevice
      - libnotify
      - libvirt
      - libxcrypt-compat
      - lm_sensors
      - lsof
      - make
      - mesa-libGLU
      - mozilla-fira-mono-fonts
      - mullvad-vpn
      - nethogs
      - p7zip
      - p7zip-plugins
      - pciutils
      - playerctl
      - podman-compose
      - podman-tui
      - podmansh
      - powerline-fonts
      - powertop
      - printer-driver-brlaser
      - procs
      - psmisc
      - pulseaudio-utils
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - rclone
      - restic
      - ripgrep
      - rocm-hip
      - rocm-opencl
      - samba
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - sd
      - solaar
      - stress-ng
      - tmux
      - traceroute
      - tree
      - udica
      - unrar
      - unzip
      - usbmuxd
      - v4l-utils
      - vazirmatn-fonts
      - virt-manager
      - virt-viewer
      - vulkan-tools
      - wireguard-tools
      - wl-clipboard
      - xpr
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

