name: cosmicplasmic
description: Greatest bootc image of all time.

base-image: ghcr.io/blue-build/base-images/fedora-cosmic-nvidia
image-version: 20251225-43

modules:
  - from-file: packages.yml
  - from-file: flatpaks.yml
  - from-file: fonts.yml
        
  # - type: akmods
  #   base: main
  #   install:
  #     - v4l2loopback
        
  - type: script
    snippets:
      - "echo test"
    scripts:
      - build.sh # run files/scripts/build.sh
      
  - type: systemd
    system:
      enabled:
        - docker.socket
        - earlyoom
      disabled:
        - initrd-parse-etc.service
        
  - type: files
    files:
      - source: system   # copies `files/usr/*` (* means everything inside it) into your image's `/usr` directory
        destination: /
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
